#include "fault.h"

const Fault errno_faults[] = {
    {"EPERM", NULL, 1, "errno", "Operation not permitted", "Missing privileges, blocked capabilities, or a protected kernel operation.", "Try the operation with the right privileges and check whether the action itself is allowed." , FAULT_KIND_ERRNO},
    {"ENOENT", NULL, 2, "errno", "No such file or directory", "Wrong path, missing file, broken symlink, or wrong current working directory.", "Check the path, list parent directories, and confirm the file really exists.", FAULT_KIND_ERRNO},
    {"ESRCH", NULL, 3, "errno", "No such process", "The target PID, thread, or process group no longer exists.", "Confirm the identifier and whether the process already exited.", FAULT_KIND_ERRNO},
    {"EINTR", NULL, 4, "errno", "Interrupted system call", "A blocking syscall was interrupted by a signal before completion.", "Retry the call when appropriate and review signal handling.", FAULT_KIND_ERRNO},
    {"EIO", NULL, 5, "errno", "I/O error", "A low-level device, filesystem, or kernel I/O failure occurred.", "Check kernel logs, hardware state, and the backing storage or device.", FAULT_KIND_ERRNO},
    {"ENXIO", NULL, 6, "errno", "No such device or address", "The target device, bus address, or special file is not available.", "Verify the device node, hardware presence, and driver support.", FAULT_KIND_ERRNO},
    {"E2BIG", NULL, 7, "errno", "Argument list too long", "The combined exec arguments and environment exceed system limits.", "Reduce arguments, shorten environment variables, or use input files.", FAULT_KIND_ERRNO},
    {"ENOEXEC", NULL, 8, "errno", "Exec format error", "The file is not a valid executable or has the wrong interpreter line.", "Check the binary format, architecture, and shebang.", FAULT_KIND_ERRNO},
    {"EBADF", NULL, 9, "errno", "Bad file descriptor", "The descriptor is invalid, already closed, or opened with incompatible mode.", "Track descriptor lifetime and verify open flags before use.", FAULT_KIND_ERRNO},
    {"ECHILD", NULL, 10, "errno", "No child processes", "A wait call was made but there is no matching child to reap.", "Check process ownership and whether the child already finished.", FAULT_KIND_ERRNO},
    {"EAGAIN", NULL, 11, "errno", "Resource temporarily unavailable", "The operation would block or a temporary limit was hit.", "Retry later, use polling, or raise relevant limits.", FAULT_KIND_ERRNO},
    {"ENOMEM", NULL, 12, "errno", "Cannot allocate memory", "The kernel could not satisfy an allocation or mapping request.", "Reduce memory pressure, inspect limits, and check for leaks.", FAULT_KIND_ERRNO},
    {"EACCES", NULL, 13, "errno", "Permission denied", "File permissions, directory traversal permissions, or SELinux/AppArmor restrictions.", "Check file mode, directory traversal permissions, and the current user.", FAULT_KIND_ERRNO},
    {"EFAULT", NULL, 14, "errno", "Bad address", "A pointer passed to the kernel is invalid or unmapped.", "Validate buffers, pointer lifetime, and memory ownership.", FAULT_KIND_ERRNO},
    {"EBUSY", NULL, 16, "errno", "Device or resource busy", "The target is in use and cannot be changed right now.", "Close users of the resource, unmount if needed, or retry later.", FAULT_KIND_ERRNO},
    {"EEXIST", NULL, 17, "errno", "File exists", "Creation failed because the destination already exists.", "Choose a different name or remove the existing destination first.", FAULT_KIND_ERRNO},
    {"EXDEV", NULL, 18, "errno", "Cross-device link", "The operation requires source and destination to be on the same filesystem.", "Use copy-and-delete instead of rename or hard-link.", FAULT_KIND_ERRNO},
    {"ENODEV", NULL, 19, "errno", "No such device", "The system cannot provide the requested device in this context.", "Check kernel support, device nodes, and the active platform.", FAULT_KIND_ERRNO},
    {"ENOTDIR", NULL, 20, "errno", "Not a directory", "A path component expected to be a directory is not one.", "Inspect each path component and correct the target path.", FAULT_KIND_ERRNO},
    {"EISDIR", NULL, 21, "errno", "Is a directory", "The operation expects a file-like target, but got a directory.", "Use the correct API for directories or point to a file instead.", FAULT_KIND_ERRNO},
    {"EINVAL", NULL, 22, "errno", "Invalid argument", "One or more arguments are outside the allowed range or violate API rules.", "Review syscall arguments, sizes, flags, and alignment assumptions.", FAULT_KIND_ERRNO},
    {"ENFILE", NULL, 23, "errno", "File table overflow", "The whole system has reached its open-file limit.", "Raise system-wide file limits or close unused descriptors.", FAULT_KIND_ERRNO},
    {"EMFILE", NULL, 24, "errno", "Too many open files", "This process reached its file descriptor limit.", "Close descriptors, audit leaks, or raise the per-process limit.", FAULT_KIND_ERRNO},
    {"ENOTTY", NULL, 25, "errno", "Inappropriate ioctl for device", "A tty-specific operation was used on an incompatible descriptor.", "Check whether the fd really refers to a terminal or supports the ioctl.", FAULT_KIND_ERRNO},
    {"EFBIG", NULL, 27, "errno", "File too large", "The file would exceed a filesystem or resource limit.", "Check file size limits, filesystem constraints, and quota.", FAULT_KIND_ERRNO},
    {"ENOSPC", NULL, 28, "errno", "No space left on device", "The filesystem has no free blocks or inodes left.", "Free disk space, clear inode exhaustion, or move the data elsewhere.", FAULT_KIND_ERRNO},
    {"ESPIPE", NULL, 29, "errno", "Illegal seek", "The descriptor refers to a non-seekable stream like a pipe or socket.", "Avoid lseek on pipes, sockets, or other stream-only handles.", FAULT_KIND_ERRNO},
    {"EROFS", NULL, 30, "errno", "Read-only filesystem", "The path is on a filesystem mounted without write access.", "Remount read-write if appropriate or choose a writable location.", FAULT_KIND_ERRNO},
    {"EMLINK", NULL, 31, "errno", "Too many links", "The hard-link limit for the file or filesystem was reached.", "Reduce link count or use a copy instead of another hard link.", FAULT_KIND_ERRNO},
    {"EPIPE", NULL, 32, "errno", "Broken pipe", "Data was written after the reader side of a pipe or socket closed.", "Handle peer shutdown, ignore SIGPIPE when needed, and retry only if safe.", FAULT_KIND_ERRNO},
    {"EDOM", NULL, 33, "errno", "Numerical argument out of domain", "A math function received a value outside its valid domain.", "Validate input before calling the math routine.", FAULT_KIND_ERRNO},
    {"ERANGE", NULL, 34, "errno", "Numerical result out of range", "A calculation overflowed, underflowed, or exceeded representable range.", "Clamp inputs, check bounds, and handle extreme values explicitly.", FAULT_KIND_ERRNO},
    {"EDEADLK", NULL, 35, "errno", "Resource deadlock avoided", "Granting the lock would create a deadlock.", "Review lock ordering and reduce circular wait conditions.", FAULT_KIND_ERRNO},
    {"ENAMETOOLONG", NULL, 36, "errno", "File name too long", "A path or path component exceeds system limits.", "Shorten the path or split deeply nested directories.", FAULT_KIND_ERRNO},
    {"ENOLCK", NULL, 37, "errno", "No locks available", "The system cannot allocate another record lock right now.", "Reduce lock usage or inspect lock-related limits.", FAULT_KIND_ERRNO},
    {"ENOSYS", NULL, 38, "errno", "Function not implemented", "The syscall or feature is missing on this kernel or build.", "Check platform support and provide a fallback path.", FAULT_KIND_ERRNO},
    {"ENOTEMPTY", NULL, 39, "errno", "Directory not empty", "Removal failed because the directory still contains entries.", "Delete or move remaining entries before removing the directory.", FAULT_KIND_ERRNO},
    {"ELOOP", NULL, 40, "errno", "Too many symbolic links encountered", "Path resolution hit a symlink loop or traversal limit.", "Inspect symlink targets and break the loop.", FAULT_KIND_ERRNO},
    {"ENOMSG", NULL, 42, "errno", "No message of desired type", "A message queue lookup found no message matching the requested type.", "Check message types and queue contents before receiving.", FAULT_KIND_ERRNO},
    {"EIDRM", NULL, 43, "errno", "Identifier removed", "The IPC object was removed while still in use.", "Recreate the IPC object and handle teardown races.", FAULT_KIND_ERRNO},
    {"ENOTSOCK", NULL, 88, "errno", "Socket operation on non-socket", "A networking API was called on a non-socket descriptor.", "Verify descriptor type before calling socket-specific functions.", FAULT_KIND_ERRNO},
    {"EDESTADDRREQ", NULL, 89, "errno", "Destination address required", "A send operation needs a peer address but none was supplied.", "Provide a destination address or connect the socket first.", FAULT_KIND_ERRNO},
    {"EMSGSIZE", NULL, 90, "errno", "Message too long", "The payload exceeds what the protocol or transport allows.", "Shrink the message or switch transport strategy.", FAULT_KIND_ERRNO},
    {"EPROTOTYPE", NULL, 91, "errno", "Protocol wrong type for socket", "The chosen protocol does not match the socket type.", "Use the correct domain, type, and protocol combination.", FAULT_KIND_ERRNO},
    {"ENOPROTOOPT", NULL, 92, "errno", "Protocol not available", "The requested socket option or protocol feature is unsupported.", "Check kernel support and guard unsupported options.", FAULT_KIND_ERRNO},
    {"EPROTONOSUPPORT", NULL, 93, "errno", "Protocol not supported", "The network stack does not implement that protocol.", "Choose a supported protocol or enable the required kernel support.", FAULT_KIND_ERRNO},
    {"EADDRINUSE", NULL, 98, "errno", "Address already in use", "Another socket already owns that local address or port.", "Pick another port, wait for release, or enable reuse options if appropriate.", FAULT_KIND_ERRNO},
    {"EADDRNOTAVAIL", NULL, 99, "errno", "Cannot assign requested address", "The local interface does not own the requested IP address.", "Bind to an existing local address or bring up the interface.", FAULT_KIND_ERRNO},
    {"ENETDOWN", NULL, 100, "errno", "Network is down", "The local network interface or stack is unavailable.", "Check link state, interface status, and network service health.", FAULT_KIND_ERRNO},
    {"ENETUNREACH", NULL, 101, "errno", "Network is unreachable", "Routing cannot find a path to the target network.", "Inspect routing tables, gateway setup, and interface configuration.", FAULT_KIND_ERRNO},
    {"ECONNABORTED", NULL, 103, "errno", "Software caused connection abort", "The local host aborted the connection before completion.", "Inspect local stack behavior and retry if the protocol allows it.", FAULT_KIND_ERRNO},
    {"ECONNRESET", NULL, 104, "errno", "Connection reset by peer", "The remote side closed the connection abruptly, usually with TCP RST.", "Handle disconnects gracefully and inspect remote-side logs.", FAULT_KIND_ERRNO},
    {"ENOBUFS", NULL, 105, "errno", "No buffer space available", "The kernel ran out of network buffers or queue capacity.", "Reduce burst load, tune buffers, and inspect system pressure.", FAULT_KIND_ERRNO},
    {"EISCONN", NULL, 106, "errno", "Transport endpoint is already connected", "The socket was connected already when another connect-like step was attempted.", "Avoid reconnecting established sockets.", FAULT_KIND_ERRNO},
    {"ENOTCONN", NULL, 107, "errno", "Transport endpoint is not connected", "The operation requires a peer connection, but none exists.", "Connect the socket first or use a datagram API that accepts a destination.", FAULT_KIND_ERRNO},
    {"ETIMEDOUT", NULL, 110, "errno", "Connection timed out", "The peer or network did not respond before the timeout expired.", "Check network reachability, firewall rules, and timeout values.", FAULT_KIND_ERRNO},
    {"ECONNREFUSED", NULL, 111, "errno", "Connection refused", "The host is reachable, but nothing accepted the connection on that port.", "Verify the service is listening and the port is correct.", FAULT_KIND_ERRNO},
    {"EHOSTUNREACH", NULL, 113, "errno", "No route to host", "Routing cannot reach the specific destination host.", "Check host routing, firewall rules, and address correctness.", FAULT_KIND_ERRNO},
    {"EALREADY", NULL, 114, "errno", "Operation already in progress", "A non-blocking network operation is still underway.", "Wait for completion with poll or select before trying again.", FAULT_KIND_ERRNO},
    {"EINPROGRESS", NULL, 115, "errno", "Operation now in progress", "A non-blocking operation started and will finish asynchronously.", "Use readiness polling and then inspect the final socket status.", FAULT_KIND_ERRNO}
};

const size_t errno_faults_count = sizeof(errno_faults) / sizeof(errno_faults[0]);
